"""Initial migration: users, readings, activation_requests tables

Revision ID: a00ec789044f
Revises: 
Create Date: 2026-01-23 23:20:25.865213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a00ec789044f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String().with_variant(sa.UUID(), 'postgresql'), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plot_number', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'user')", name='check_valid_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('activation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('activated_by', sa.String().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['activated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('day_reading', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('night_reading', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readings_user_id'), 'readings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readings_user_id'), table_name='readings')
    op.drop_table('readings')
    op.drop_table('activation_requests')
    op.drop_table('users')
    # ### end Alembic commands ###
